// =============================================================================
// THE SHARED DESIGN TOKENS. One palette, two products.
// =============================================================================
// This file is part of `uikit/`, which is BYTE-IDENTICAL in every tool that
// uses it (see README.md). Nothing app-specific belongs here: a product's name,
// mark and favicon live in its own `src/brand.ts`, outside this folder, which
// is why the folder can be copied wholesale between repositories.
//
// One config drives three layers so they cannot drift apart:
//   1. CSS custom properties (:root / [data-theme="dark"]) - generated by
//      renderRootCss() and inlined into <head> by vitePluginBrand.ts, so there
//      is no flash of the wrong theme.
//   2. Ant Design tokens - antd.ts reads this file instead of hardcoding.
//   3. The uikit's own stylesheets and primitives, which name only variables.
//
// Keep this file dependency-free: it is imported by both the browser bundle and
// the Node-side Vite plugin.
// -----------------------------------------------------------------------------

/** A full set of themeable colors for one mode (light or dark). */
export interface Palette {
  // Primary (brand) and its variants
  brand: string;
  brandStrong: string; // hover / pressed brand
  brandSoft: string; // tinted fill behind selected/brand surfaces
  brandBorder: string;
  // Secondary accent. Defaults to brandStrong so it is inert until you set it;
  // exposed as var(--secondary) for your own accents.
  secondary: string;
  // Sidebar / navigation rail. `navBg` is a MATERIAL: a translucent fill the
  // page shows faintly through, so give it an alpha and let `components.css`
  // put the blur behind it.
  navBg: string;
  navBgHover: string;
  navBgActive: string;
  navFg: string;
  /** Type that has to hold its own on the navigation - the product's name, the
   *  signed-in person - as opposed to an item's quieter label. It is a separate
   *  token because the navigation is a light material in light mode and a dark
   *  one in dark mode: "white" was correct for exactly one of those. */
  navFgStrong: string;
  navFgActive: string;
  navBorder: string;
  // Surfaces: canvas (page) < surface (content) < surface2 (raised or sunken
  // well - the same value serves both, because a recessed panel and a raised
  // one differ by their shadow, not by their fill)
  canvas: string;
  surface: string;
  surface2: string;
  border: string;
  borderStrong: string;
  illSurface: string; // "paper" fill inside the state illustrations
  // Text
  text: string;
  text2: string;
  text3: string;
  // Semantic status triples (foreground / pastel background / border)
  ok: string; okBg: string; okBd: string;
  pending: string; pendingBg: string; pendingBd: string;
  review: string; reviewBg: string; reviewBd: string;
  danger: string; dangerBg: string; dangerBd: string;
  // The "you are here" wash: a highlighter over the thing a link led to. It is
  // not a status - nothing is wrong or pending about a value somebody asked to
  // be shown - so it gets its own colour rather than borrowing one that means
  // something.
  markBg: string; markBd: string;
  // Provenance (base = inherited from a shared layer, inherit = neutral)
  base: string; baseBg: string; baseBd: string;
  inherit: string; inheritBg: string; inheritBd: string;
  // The three move destinations, as foreground/background/border triples: the
  // colour of the button that moves a release INTO an environment, and of the
  // tag that names it. Unlike envColors - an identity MARK, one hue in both
  // modes - these are themed: a slate sandbox tag is near-white type on dark
  // and near-black on light, while filled lab cyan reads the same either way.
  envSandbox: string; envSandboxBg: string; envSandboxBd: string;
  envLab: string; envLabBg: string; envLabBd: string;
  envProd: string; envProdBg: string; envProdBd: string;
  // Severity, and the surface each severity dot sits on. A FIVE-step scale
  // rather than the four semantic tones, because "unknown" is a real answer
  // that must not read as "none": a package nobody has scanned is not a clean
  // one. COLOUR IS NEVER THE ONLY SIGNAL - every severity is also a word and a
  // dot whose fill differs - so these survive greyscale and colour blindness.
  sevCritical: string; sevHigh: string; sevMedium: string; sevLow: string; sevUnknown: string;
  // Known-exploited: worse than critical, and a different hue so it cannot be
  // mistaken for critical red on a graph or a tag.
  sevKev: string; sevKevBg: string;
  sevCriticalBg: string; sevHighBg: string; sevMediumBg: string; sevLowBg: string; sevUnknownBg: string;
  // The verdict of a comparison. `inconclusive` is deliberately not a grey that
  // reads as "nothing happened": it is a state with an action in it (go and
  // look at the rest), and looking like an empty result is how it gets ignored.
  vBetter: string; vWorse: string; vUnchanged: string; vInconclusive: string;
}

/** The palette-and-metrics half of a theme. Identity lives in brand.ts. */
export interface ThemeTokens {
  /** Shape tokens fed to Ant Design. */
  shape: { borderRadius: number; controlHeight: number };
  /** Type tokens fed to Ant Design. */
  type: { fontFamily: string; monoFamily: string };
  light: Palette;
  dark: Palette;
  /** Environment identity colors (which environment an instance runs in). */
  envColors: Record<string, string>;
}

// Palette key -> CSS custom property. Every stylesheet and every primitive in
// this kit names one of these and never a hex, which is what makes a rebrand
// one edit instead of a search.
export const VAR_MAP: Array<[keyof Palette, string]> = [
  ["brand", "--brand"], ["brandStrong", "--brand-strong"], ["brandSoft", "--brand-soft"],
  ["brandBorder", "--brand-border"], ["secondary", "--secondary"],
  ["navBg", "--nav-bg"], ["navBgHover", "--nav-bg-hover"], ["navBgActive", "--nav-bg-active"],
  ["navFg", "--nav-fg"], ["navFgStrong", "--nav-fg-strong"],
  ["navFgActive", "--nav-fg-active"], ["navBorder", "--nav-border"],
  ["canvas", "--canvas"], ["surface", "--surface"], ["surface2", "--surface-2"],
  ["border", "--border"], ["borderStrong", "--border-strong"], ["illSurface", "--ill-surface"],
  ["text", "--text"], ["text2", "--text-2"], ["text3", "--text-3"],
  ["ok", "--c-ok"], ["okBg", "--c-ok-bg"], ["okBd", "--c-ok-bd"],
  ["pending", "--c-pending"], ["pendingBg", "--c-pending-bg"], ["pendingBd", "--c-pending-bd"],
  ["review", "--c-review"], ["reviewBg", "--c-review-bg"], ["reviewBd", "--c-review-bd"],
  ["danger", "--c-danger"], ["dangerBg", "--c-danger-bg"], ["dangerBd", "--c-danger-bd"],
  ["markBg", "--c-mark-bg"], ["markBd", "--c-mark-bd"],
  ["base", "--c-base"], ["baseBg", "--c-base-bg"], ["baseBd", "--c-base-bd"],
  ["inherit", "--c-inherit"], ["inheritBg", "--c-inherit-bg"], ["inheritBd", "--c-inherit-bd"],
  ["envSandbox", "--env-sandbox"], ["envSandboxBg", "--env-sandbox-bg"], ["envSandboxBd", "--env-sandbox-bd"],
  ["envLab", "--env-lab"], ["envLabBg", "--env-lab-bg"], ["envLabBd", "--env-lab-bd"],
  ["envProd", "--env-prod"], ["envProdBg", "--env-prod-bg"], ["envProdBd", "--env-prod-bd"],
  ["sevCritical", "--sev-critical"], ["sevHigh", "--sev-high"], ["sevMedium", "--sev-medium"],
  ["sevLow", "--sev-low"], ["sevUnknown", "--sev-unknown"],
  ["sevKev", "--sev-kev"], ["sevKevBg", "--sev-kev-bg"],
  ["sevCriticalBg", "--sev-critical-bg"], ["sevHighBg", "--sev-high-bg"],
  ["sevMediumBg", "--sev-medium-bg"], ["sevLowBg", "--sev-low-bg"],
  ["sevUnknownBg", "--sev-unknown-bg"],
  ["vBetter", "--v-better"], ["vWorse", "--v-worse"], ["vUnchanged", "--v-unchanged"],
  ["vInconclusive", "--v-inconclusive"],
];

// -----------------------------------------------------------------------------
// Defaults: the identity these tools ship with. Change values via a PRESET
// below rather than editing these, so the baseline is always there to diff
// against - and so both products move together when one of them moves.
//
// THE PALETTE is neutral first: cool greys (#102C3C type, #F7F9FA ground,
// #E3E9ED rules) with AT&T blue #009FDF kept for what can be acted on -
// the selected navigation entry, primary actions, links, selections. Wells,
// borders and decoration stay grey, so the blue always means "this does
// something".
//
// In dark mode the cards are the lighter layer, so a panel still reads as
// lifted off the page.
// -----------------------------------------------------------------------------
export const defaultTokens: ThemeTokens = {
  // 8 and 32: a control the size of a macOS push button, with the continuous
  // corner the whole platform rounds to. 6/30 read as a web form.
  shape: { borderRadius: 8, controlHeight: 32 },
  type: {
    // San Francisco first, by its real names as well as through -apple-system,
    // so the face is right on a Mac and on an iPad viewing the same page. Inter
    // is the closest widely-installed stand-in and sits ahead of the platform
    // defaults for everyone else.
    fontFamily:
      `"Inter Variable", Inter, -apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", "Segoe UI Variable Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif`,
    // ui-monospace resolves to SF Mono on Apple platforms, which is the point.
    monoFamily:
      `ui-monospace, "SF Mono", SFMono-Regular, "JetBrains Mono", Menlo, Consolas, "Liberation Mono", monospace`,
  },
  light: {
    brand: "#009fdf", brandStrong: "#0086bd", brandSoft: "#eef8fc", brandBorder: "#bfe3f3",
    secondary: "#7657a8",
    navBg: "#ffffff", navBgHover: "#f3f5f7", navBgActive: "#eef8fc",
    navFg: "#5b6774", navFgStrong: "#102332", navFgActive: "#0086bd",
    navBorder: "#e6eaee",
    canvas: "#f5f7f9", surface: "#ffffff", surface2: "#f4f7f9",
    border: "#e4e9ed", borderStrong: "#d2d9df", illSurface: "#ffffff",
    text: "#102332", text2: "#4b5b68", text3: "#8a99a5",
    markBg: "#fdf3d8", markBd: "#eed9a4",
    ok: "#157f3d", okBg: "#e9f7ee", okBd: "#bfe7cb",
    pending: "#a15c07", pendingBg: "#fdf3e3", pendingBd: "#f2ddb0",
    review: "#0086bd", reviewBg: "#eef8fc", reviewBd: "#bfe3f3",
    danger: "#cf3148", dangerBg: "#fdeef0", dangerBd: "#f6c4cc",
    base: "#7657a8", baseBg: "#f4f0fa", baseBd: "#dcd0ee",
    inherit: "#5f7482", inheritBg: "#f3f6f8", inheritBd: "#e3e9ed",
    // Move destinations use light fills and borders; production's orange is
    // never danger red.
    envSandbox: "#172b4d", envSandboxBg: "#f1f3f5", envSandboxBd: "#d8dde3",
    envLab: "#00749f", envLabBg: "#e9f7fc", envLabBd: "#b8dff0",
    envProd: "#d94f00", envProdBg: "#fff0e3", envProdBd: "#ffd0ad",
    // The severity ramp is the MARK's colour first - the dot, the bar, the
    // meter - and the word's second. That ordering is what let it become
    // modern: the old values were picked to clear 4.5:1 as text on white, and
    // any yellow dark enough to do that is olive, any orange is brown. The
    // panel read as army surplus.
    //
    // These are vivid at the hue they are meant to be: a real vermilion, a real
    // gold, a real emerald. They are FILLS - a dot, a bar segment, a meter -
    // never the colour of a word, so nothing here is read as text and nothing
    // has to be dulled to be readable. Medium especially: a gold that clears
    // 4.5:1 on white does not exist, which is the whole reason this scale used
    // to look like army surplus.
    //
    // The word keeps its meaning without the hue - it is spelled out, and the
    // dot differs in FILL as well as colour (critical and high solid, medium
    // and low ringed, unknown dashed) - so nothing about the scale depends on
    // being able to read a colour. Never set one of these as `color` on text.
    // Critical vermillion, high orange, medium a clear gold (not orange-adjacent).
    // KEV is a deep crimson-magenta: as alarming as critical, never the same red.
    sevCritical: "#cf3148", sevHigh: "#f56416", sevMedium: "#e6a700",
    sevLow: "#1d9d55", sevUnknown: "#8a99a5",
    sevKev: "#9f1239", sevKevBg: "#fdeef2",
    sevCriticalBg: "#fdeef0", sevHighBg: "#fdeee2", sevMediumBg: "#fdf6d8",
    sevLowBg: "#e7f7ec", sevUnknownBg: "#f1f3f5",
    vBetter: "#157f3d", vWorse: "#c22739", vUnchanged: "#6e7680", vInconclusive: "#5856d6",
  },
  dark: {
    // SEEDS for Ant's dark algorithm, which dulls whatever it is given;
    // resolvePalette in antd.ts hands the stylesheet what is really painted.
    brand: "#1fb4ee", brandStrong: "#4cc4f2", brandSoft: "rgba(0, 159, 223, 0.14)",
    brandBorder: "rgba(0, 159, 223, 0.4)", secondary: "#9b7fd0",
    navBg: "#111518", navBgHover: "rgba(230, 237, 243, 0.05)",
    navBgActive: "rgba(0, 159, 223, 0.14)",
    navFg: "#aab7c3", navFgStrong: "#e6edf3", navFgActive: "#00b5e2",
    navBorder: "#22292f",
    canvas: "#0e1215", surface: "#161b1f", surface2: "#1d2328",
    border: "#29313a", borderStrong: "#39434d", illSurface: "#1d2328",
    text: "#e8edf0", text2: "#a9b5bd", text3: "#7c8a94",
    markBg: "rgba(230, 167, 0, 0.16)", markBd: "rgba(230, 167, 0, 0.42)",
    ok: "#6cc84d", okBg: "rgba(79, 174, 50, 0.16)", okBd: "rgba(79, 174, 50, 0.42)",
    pending: "#f0b929", pendingBg: "rgba(230, 167, 0, 0.16)", pendingBd: "rgba(230, 167, 0, 0.42)",
    review: "#00b5e2", reviewBg: "rgba(0, 159, 219, 0.16)", reviewBd: "rgba(0, 159, 219, 0.42)",
    danger: "#e8627a", dangerBg: "rgba(209, 59, 86, 0.18)", dangerBd: "rgba(209, 59, 86, 0.45)",
    base: "#a58bd6", baseBg: "rgba(119, 86, 168, 0.22)", baseBd: "rgba(119, 86, 168, 0.5)",
    inherit: "#aab7c3", inheritBg: "rgba(170, 183, 195, 0.12)", inheritBd: "rgba(170, 183, 195, 0.3)",
    // The same three destinations, restated for the dark canvas.
    envSandbox: "#f5f7fa", envSandboxBg: "#303b4a", envSandboxBd: "#4a5568",
    envLab: "#5ac7ed", envLabBg: "rgba(0, 159, 219, 0.16)", envLabBd: "rgba(0, 159, 219, 0.42)",
    envProd: "#ff8a30", envProdBg: "#5a3218", envProdBd: "#8a4a1f",
    // The system palette, exactly: these are not seeds and never go through
    // Ant's algorithm, so the dark scale can be the real values rather than a
    // solve. The old medium was a desaturated #e0b93a - a yellow apologising
    // for being one - where the platform's own is unmissable.
    sevCritical: "#e8627a", sevHigh: "#ff8a2a", sevMedium: "#f0b929",
    sevLow: "#4fae32", sevUnknown: "#7b8b98",
    // Hot rose on dark canvas; critical stays vermillion so the two never merge.
    sevKev: "#ff2d55", sevKevBg: "rgba(255, 45, 85, 0.18)",
    sevCriticalBg: "rgba(255, 69, 58, 0.18)", sevHighBg: "rgba(255, 159, 10, 0.18)",
    sevMediumBg: "rgba(255, 214, 10, 0.18)", sevLowBg: "rgba(48, 209, 88, 0.18)",
    sevUnknownBg: "rgba(152, 152, 157, 0.18)",
    vBetter: "#30d158", vWorse: "#ff6961", vUnchanged: "#98989d", vInconclusive: "#a5a3ff",
  },
  // Environment identity, on the system palette too - but these stay the same
  // in both modes on purpose: an environment does not change identity when the
  // lights go out. These are MARKS - a dot, an icon. The themed surfaces an
  // environment paints (the move buttons, the stage tags) are the envSandbox /
  // envLab / envProd triples in the palettes above, which DO flip with the mode.
  envColors: {
    production: "#ff6b2c", prod: "#ff6b2c",     // vibrant tangerine
    staging: "#d946ef",                          // vibrant fuchsia
    development: "#10b981", nonprod: "#10b981",  // fresh emerald
    available: "#157f3d",
    lab: "#009fdf",                              // bright electric blue
    sandbox: "#4a5d7e",                          // deep slate blue-grey
    scanned: "#ef4444",                          // vivid red, the release timeline's scan step
  },
};

// -----------------------------------------------------------------------------
// PRESETS. A preset is a named look built on top of the defaults. Ship several;
// an operator picks ONE with a single line below, and BOTH tools follow, which
// is the whole point of this folder being identical in each of them.
//
//  - "default"    the system palette on a translucent chrome: what both tools
//                 ship, and what the rest of this file is written around.
//  - "graphite"   the same shapes with the colour taken out of the chrome: a
//                 near-neutral accent for a deployment that wants the data to
//                 be the only saturated thing on screen. (Its flatter elevation
//                 lives in tokens.css under :root[data-preset="graphite"].)
//  - "gateway"    the cyan corporate mark, for a deployment that must wear it.
//
// A preset never brings back the opaque navy chrome or the filled active pill:
// the navigation is a light column in every one of them. What a preset changes
// is the ACCENT and the temperature of the neutrals.
// -----------------------------------------------------------------------------
export const presets: Record<string, DeepPartial<ThemeTokens>> = {
  default: {},
  graphite: {
    shape: { borderRadius: 8 },
    light: {
      brand: "#3a3a3c", brandStrong: "#1d1d1f", brandSoft: "#eeeef0", brandBorder: "#cfcfd4",
      secondary: "#0071e3",
      navBg: "#ffffff", navBgActive: "#eeeef0", navFgActive: "#1d1d1f",
      canvas: "#ededf0", surface: "#ffffff", surface2: "#f4f4f6",
      border: "#e2e2e5", borderStrong: "#cfcfd4",
      review: "#3a3a3c", reviewBg: "#eeeef0", reviewBd: "#cfcfd4",
    },
    dark: {
      brand: "#d8d8dc", brandStrong: "#ececf0", brandSoft: "rgba(200, 200, 208, 0.16)",
      brandBorder: "rgba(200, 200, 208, 0.4)", secondary: "#44b2ff",
      navBg: "#18181a", navBgActive: "rgba(200, 200, 208, 0.14)", navFgActive: "#ececf0",
      canvas: "#161618", surface: "#1f1f22", surface2: "#28282b",
      border: "#333336", borderStrong: "#454549",
      review: "#d8d8dc", reviewBg: "rgba(200, 200, 208, 0.14)",
      reviewBd: "rgba(200, 200, 208, 0.36)",
    },
  },
  gateway: {
    light: {
      brand: "#007ba8", brandStrong: "#00607f", brandSoft: "#e3f4fb", brandBorder: "#a9d9ec",
      secondary: "#00607f",
      navBg: "#ffffff", navBgActive: "#e3f4fb", navFgActive: "#007ba8",
      review: "#007ba8", reviewBg: "#e3f4fb", reviewBd: "#a9d9ec",
    },
    dark: {
      brand: "#45b8e3", brandStrong: "#6ac9ea", brandSoft: "rgba(0, 159, 219, 0.16)",
      brandBorder: "rgba(0, 159, 219, 0.45)", secondary: "#6ac9ea",
      navBg: "#141c22", navBgActive: "rgba(0, 159, 219, 0.16)", navFgActive: "#6ac9ea",
      review: "#45b8e3", reviewBg: "rgba(0, 159, 219, 0.14)", reviewBd: "rgba(0, 159, 219, 0.4)",
    },
  },
};

// THE SWITCH. Change this one value and every tool that shares this folder
// changes with it. Leave it "default" to ship unchanged.
export const ACTIVE_PRESET = "default";

// -----------------------------------------------------------------------------
// LOCAL OVERRIDES. Deep-merged over the active preset. Whatever you put here
// applies to THIS repository only, so anything in it is a deliberate decision
// to let the two tools differ. Keep it empty unless you mean that.
// -----------------------------------------------------------------------------
export const tokenOverrides: DeepPartial<ThemeTokens> = {};

// --- machinery (usually no need to touch below) ------------------------------

export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function deepMerge<T>(base: T, over: DeepPartial<T>): T {
  if (!isObject(base) || !isObject(over)) return (over as T) ?? base;
  const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
  for (const [k, v] of Object.entries(over)) {
    const b = (base as Record<string, unknown>)[k];
    out[k] = isObject(b) && isObject(v) ? deepMerge(b, v as DeepPartial<unknown>) : v;
  }
  return out as T;
}

export { deepMerge };

/** The resolved, active tokens: defaults, then the chosen preset, then any
 *  local overrides on top. */
export const tokens: ThemeTokens = deepMerge(
  deepMerge(defaultTokens, presets[ACTIVE_PRESET] ?? {}),
  tokenOverrides,
);

/** One mode's palette as `--var: value;` declarations. */
function paletteToCss(p: Palette): string {
  return VAR_MAP.map(([key, cssVar]) => `${cssVar}: ${p[key]};`).join(" ");
}

/** The colour layer, as a stylesheet.
 *
 *  `resolve` is how the two halves are kept honest: the caller (the Vite
 *  plugin) hands in `resolvePalette` from antd.ts, which asks the component
 *  library what it is actually going to paint. Without it the stylesheet would
 *  state the SEED colours and the components would paint the shades Ant
 *  derives from them, and in dark mode those are visibly different.
 *
 *  The DEFAULT palette lands on :root; every OTHER preset is emitted scoped to
 *  :root[data-preset="<name>"], so switching preset (the attribute the brand
 *  plugin stamps on <html> at parse time) flips the whole palette with no
 *  rebuild, and every look always ships together. Local overrides apply on top
 *  of whichever preset is active. */
export function renderRootCss(resolve?: (p: Palette, dark: boolean) => Palette): string {
  const r = resolve ?? ((p: Palette) => p);
  const base = deepMerge(defaultTokens, tokenOverrides);
  const blocks = [
    `:root { ${paletteToCss(r(base.light, false))} }`,
    `[data-theme="dark"] { ${paletteToCss(r(base.dark, true))} }`,
  ];
  for (const [name, over] of Object.entries(presets)) {
    if (name === "default" || !over) continue;
    const merged = deepMerge(deepMerge(defaultTokens, over), tokenOverrides);
    blocks.push(`:root[data-preset="${name}"] { ${paletteToCss(r(merged.light, false))} }`);
    blocks.push(
      `[data-theme="dark"][data-preset="${name}"] { ${paletteToCss(r(merged.dark, true))} }`,
    );
  }
  return blocks.join("\n");
}
